# Generated by Django 4.2.3 on 2023-07-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="monthly_income",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="client",
            name="net_worth",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
