# Generated by Django 4.2.3 on 2023-07-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_payment_due_date_expectedpayment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mobile_number",
            field=models.CharField(max_length=12),
        ),
    ]
