# Generated by Django 4.2.3 on 2023-07-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_remove_payment_loan_id_remove_payment_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="issue_date",
            field=models.DateField(null=True),
        ),
    ]
