# Generated by Django 4.2.3 on 2023-07-28 17:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_loan_issue_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="expected_payment_id",
        ),
        migrations.AddField(
            model_name="payment",
            name="client_id",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="core.client"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="due_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="payment",
            name="is_late",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="payment",
            name="loan_id",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="core.loan"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(default="Pending", max_length=50),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="payment",
            name="date_paid",
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name="ExpectedPayment",
        ),
    ]
