# Generated by Django 4.2.3 on 2023-07-28 17:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_remove_payment_expected_payment_id_payment_client_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loan",
            old_name="client_id",
            new_name="client",
        ),
    ]
