# Generated by Django 4.2.3 on 2023-07-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_rename_client_id_loan_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="amount_to_pay",
            field=models.IntegerField(default=0),
        ),
    ]
