# Generated by Django 4.2.3 on 2023-07-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_loan_amount_to_pay"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(default="client", max_length=50),
        ),
    ]
