# Generated by Django 4.2.3 on 2023-07-12 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loanid', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('terms', models.IntegerField()),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('mobilenumber', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication.user')),
                ('type', models.CharField(max_length=10)),
            ],
            bases=('authentication.user',),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication.user')),
                ('salary', models.IntegerField()),
                ('type', models.CharField(max_length=10)),
            ],
            bases=('authentication.user',),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentid', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('payment_date', models.DateField()),
                ('loanid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.loan')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionReport',
            fields=[
                ('transactionid', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_date', models.DateField()),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.admin')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.client')),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='clientid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.client'),
        ),
    ]
