# Generated by Django 4.2.3 on 2023-07-15 00:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loan",
            old_name="loanid",
            new_name="loan_id",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="paymentid",
            new_name="payment_id",
        ),
        migrations.RenameField(
            model_name="transactionreport",
            old_name="transactionid",
            new_name="transaction_id",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="firstname",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="lastname",
            new_name="last_name",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="mobilenumber",
            new_name="mobile_number",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="userid",
            new_name="user_id",
        ),
    ]
